### ISSUE TITLE
Cannot read particle distribution with gpt.easygdf

### ISSUE THREAD

**Issue by petr-lanl** [ColwynGulliford/distgen#17]
I am trying to load distgen generated initial distribution, gpt.particles.gdf , with lume-gpt version of easygdf. I am getting a wrong GDF Magic number (544809080). Using distgen v2.0.2 and lume-gpt v0.7.9. Any idea why that would be?

Here is my distgen.yaml:
```
species: electron
n_particle: 2000
random_type: hammersley

total_charge:
  units: pC
  value: 250

r_dist:
  n_sigma_cutoff:
    units: dimensionless
    value: 1.2
  sigma_xy:
    units: mm
    value: 1
  type: rg

t_dist:
  type: sg
  p:
    units: dimensionless
    value: 10
  sigma_t: 
    units: ps
    value: 1
   
output:
  file: gpt.particles.gdf
  type: gpt

start:
  MTE:
    units: meV
    value: 5
  type: cathode

transforms:
  order:
  - t2
  - t3
  - t4
  t2:
    sigma_xy:
      units: mm
      value: 0.260
    type: set_stdxy x:y
  t3:
    sigma_t:
      units: ps
      value: 2.36 
    type: set_std t
  t4:
    avg_x:
      units: mm
      value: 0.0
    type: set_avg x
```
